version: '3.1'
services:
  request-info:
    image: renukafernando/request-info:v2
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
