apiVersion: apps/v1
kind: Deployment
metadata:
  name: request-info-deployment
  labels:
    app: request-info
spec:
  replicas: 1
  selector:
    matchLabels:
      app: request-info
  template:
    metadata:
      labels:
        app: request-info
    spec:
      containers:
      - name: request-info
        image: cakebakery/request-info:v2
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
