name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  release:
    types: [ "published" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build AMD64 Binary
      run: env GOOS=linux GOARCH=amd64 go build -o request-info-amd64 .
    
    - name: Build ARM64 Binary
      run: env GOOS=linux GOARCH=arm64 go build -o request-info-arm64 .
    
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: renukafernando/request-info:latest
